[package]
name = "logix_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logix_core = { path = "../logix_core" }
rand = "0.8.5"
log = "0.4.21"
env_logger = "0.11.3"
thiserror = "1.0.24"
